import jestConfig from '@map-colonies/eslint-config/jest';
import tsBaseConfig from '@map-colonies/eslint-config/ts-base';

export default [
  {
    ignores: ['**/*.js', 'dist/**', 'src/AUTOGENERATED/**'],
  },
  ...jestConfig,
  ...tsBaseConfig,
  {
    languageOptions: {
      parserOptions: {
        projectService: false,
        project: './tsconfig.lint.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: 'type|of' }],
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
    },
  },
  {
    files: ['src/graphql/**/*.ts'],
    rules: {
      'import-x/exports-last': 'off',
    },
  },
  {
    files: ['src/graphql/resolvers/**/*.ts'],
    rules: {
      '@typescript-eslint/explicit-member-accessibility': ['error', { overrides: { parameterProperties: 'off' } }],
    },
  },
];
