import fs from 'fs';
import path from 'path';
import { inject, singleton } from 'tsyringe';
import { Logger } from '@map-colonies/js-logger';
import { Services } from '../constants';
import { LayerRasterRecord } from '../../AUTOGENERATED/GraphQLClass';
import { RasterBackupParams } from '../../graphql/inputTypes';
import { stringifyObject } from '../../utils';

const METADATA_MOCK_PATH = path.join(__dirname, '../../graphql/MOCKS/raster-backup/Cyprus_backup-restore_metadata.json');

type RasterBackupMetadataMock = Omit<LayerRasterRecord, 'id'>;

@singleton()
export class RasterBackupManager {
  public constructor(@inject(Services.LOGGER) private readonly logger: Logger) {}

  public async getMetadata(params: RasterBackupParams): Promise<LayerRasterRecord> {
    this.logger.info(`[RasterBackupManager][getMetadata] ${stringifyObject(params)}`);
    const raw = fs.readFileSync(METADATA_MOCK_PATH, 'utf-8');
    const mock = JSON.parse(raw) as RasterBackupMetadataMock;
    return Promise.resolve({ id: mock.productId as string, ...mock });
  }
}
