import fs from 'fs';
import path from 'path';
import { inject, singleton } from 'tsyringe';
import { Logger } from '@map-colonies/js-logger';
import { Services } from '../constants';
import { LayerRasterRecord } from '../../AUTOGENERATED/GraphQLClass';
import { GeojsonFeatureCollection } from '../../graphql/export-layer';
import { RasterBackupParams, RevertRasterLayerData } from '../../graphql/inputTypes';
import { requestExecutor, stringifyObject } from '../../utils';
import { IConfig, IContext, IService } from '../interfaces';

const METADATA_MOCK_PATH = path.join(__dirname, '../../graphql/MOCKS/raster-backup/Cyprus_backup-restore_metadata.json');
const OUTER_PERIMETER_MOCK_PATH = path.join(__dirname, '../../graphql/MOCKS/raster-backup/center_2st_footprint.geojson');

type RasterBackupMetadataMock = Omit<LayerRasterRecord, 'id'>;

@singleton()
export class RasterBackupManager {
  private readonly service: IService;
  private readonly dataInterventionCredential: string;

  public constructor(@inject(Services.CONFIG) private readonly config: IConfig, @inject(Services.LOGGER) private readonly logger: Logger) {
    this.service = this.config.get('rasterBackup');
    this.dataInterventionCredential = this.config.get('deleteLayerApprovalCode');
  }

  public async getMetadata(params: RasterBackupParams): Promise<LayerRasterRecord> {
    this.logger.info(`[RasterBackupManager][getMetadata] ${stringifyObject(params)}`);
    const raw = fs.readFileSync(METADATA_MOCK_PATH, 'utf-8');
    const mock = JSON.parse(raw) as RasterBackupMetadataMock;
    return Promise.resolve({ id: mock.productId as string, ...mock });
  }

  public async getOuterPerimeter(params: RasterBackupParams): Promise<GeojsonFeatureCollection> {
    this.logger.info(`[RasterBackupManager][getOuterPerimeter] ${stringifyObject(params)}`);
    const raw = fs.readFileSync(OUTER_PERIMETER_MOCK_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as GeojsonFeatureCollection;
    // mst-gql on the client always requests `id` and treats a `null` id as an MST identifier
    // resolution attempt, which throws. Features are not required to carry an `id` per the
    // GeoJSON spec, so synthesize a stable one instead of relying on the source data for it.
    parsed.features = parsed.features.map((feature, index) => ({
      ...feature,
      id: feature.id ?? `OuterPerimeter_${index}`,
    }));
    return Promise.resolve(parsed);
  }

  public async revert(data: RevertRasterLayerData, ctx: IContext): Promise<void> {
    this.logger.info(`[Ingestion][Raster][revert] ${stringifyObject(data)}`);

    if (data.approvalCode !== this.dataInterventionCredential) {
      throw new Error('[BFF][IngestionManagerRaster][revert] Wrong Approval Code');
    }

    const MOCK_CONFLICTING_JOB_ID = 'b3df1d88-6c06-4995-849b-f2c9c022f079';
    throw new Error(`Revert failed, job ${MOCK_CONFLICTING_JOB_ID} is already in progress`);

    await requestExecutor(
      {
        url: `${this.service.url}/ingestion/restore`,
        exposureType: this.service.exposureType,
      },
      'POST',
      {
        data: {
          productId: data.productId,
          productType: data.productType,
          productVersion: data.productVersion,
          approver: data.approverName,
        },
      },
      ctx
    );
  }
}
