/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { container } from 'tsyringe';
import { Resolver, Query } from 'type-graphql';
import { Logger } from '@map-colonies/js-logger';
import { mcEnums, PolygonPartRecord } from '../../AUTOGENERATED/GraphQLClass';
import { Services } from '../../common/constants';
import { getDescriptors } from '../../helpers/entityDescriptor.helpers';
import { extractErrorMessage } from '../../utils';
import { EntityDescriptor, MCEnums } from '../entityDescriptor';

@Resolver()
export class EntityDescriptorResolver {
  private readonly logger: Logger;

  public constructor() {
    this.logger = container.resolve(Services.LOGGER);
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  @Query((type) => [EntityDescriptor])
  public async entityDescriptors(): Promise<EntityDescriptor[]> {
    try {
      const data = await Promise.resolve(getDescriptors());
      return data;
    } catch (err) {
      this.logger.error(`[EntityDescriptor][entityDescriptors][ERROR] ${extractErrorMessage(err)}`);
      throw err;
    }
  }

  @Query((type) => MCEnums)
  public async getMcEnums(): Promise<MCEnums> {
    try {
      const data = await Promise.resolve(mcEnums);
      return { enums: data };
    } catch (err) {
      this.logger.error(`[EntityDescriptor][getMcEnums][ERROR] ${extractErrorMessage(err)}`);
      throw err;
    }
  }

  @Query((type) => [PolygonPartRecord])
  public async getPolygonPartsDUMMY(): Promise<PolygonPartRecord[]> {
    try {
      const data = await Promise.resolve([]);
      return data;
    } catch (err) {
      this.logger.error(`[EntityDescriptor][getPolygonPartsDUMMY][ERROR] ${extractErrorMessage(err)}`);
      throw err;
    }
  }
}
