import { container } from 'tsyringe';
import { Arg, Query, Resolver } from 'type-graphql';
import { Logger } from '@map-colonies/js-logger';
import { Services } from '../../common/constants';
import { RasterBackupManager } from '../../common/raster-backup-manager/raster-backup-manager';
import { extractErrorMessage } from '../../utils';
import { LayerRasterRecord } from '../../AUTOGENERATED/GraphQLClass';
import { RasterBackupParams } from '../inputTypes';

@Resolver()
export class RasterBackupResolver {
  private readonly logger: Logger;
  private readonly rasterBackupManager: RasterBackupManager;

  public constructor() {
    this.logger = container.resolve(Services.LOGGER);
    this.rasterBackupManager = container.resolve(RasterBackupManager);
  }

  @Query((type) => LayerRasterRecord, { nullable: true })
  public async getRasterBackupMetadata(
    @Arg('data')
    data: RasterBackupParams
  ): Promise<LayerRasterRecord | null> {
    try {
      const metadata = await this.rasterBackupManager.getMetadata(data);
      return metadata;
    } catch (err) {
      this.logger.error(`[RasterBackup][getRasterBackupMetadata][ERROR] ${extractErrorMessage(err)}`);
      throw err;
    }
  }
}
