apiVersion: v2
description: Helm chart to deploy Catalog App
name: catalog-web-app-bff
version: 4.5.0
appVersion: 4.5.0
dependencies:
  - name: helm-common
    version: 1.0.2
    repository: oci://acrarolibotnonprod.azurecr.io/helm/library
