import { Stream } from 'stream';
import { Logger } from '@map-colonies/js-logger';
import { requestExecutor } from '../../utils';
import { IConfig, IContext, IService } from '../interfaces';
import { ExplorerGetById, ExplorerGetByPath, ExplorerResolveMetadataAsModel } from '../../graphql/inputTypes';
import { File } from '../../graphql/storage-explorer';
import { LayerRasterRecord } from '../../AUTOGENERATED/GraphQLClass';
// import searchMockData from '../../graphql/MOCKS/storage-explorer/mock_utils';
// import RASTER_MOCK_DATA, { MOCK_FILE } from '../../graphql/MOCKS/storage-explorer/RASTER/MOCK_DATA';
import { IStorageExplorerManagerService } from './storage-explorer.interface';

export class StorageExplorerManagerRaster implements IStorageExplorerManagerService {
  private readonly service: IService;

  public constructor(private readonly config: IConfig, private readonly logger: Logger) {
    this.service = this.config.get('storageExplorerServices.raster');
  }

  public async getDirectory(data: ExplorerGetByPath, ctx: IContext): Promise<File[]> {
    this.logger.info(`[StorageExplorerManagerRaster][getDirectory] fetching directory with data: ${JSON.stringify(data)}.`);

    // REAL LOGIC
    const res = await requestExecutor(
      {
        url: `${this.service.url}/explorer/directory?path=${data.path}`,
        exposureType: this.service.exposureType,
      },
      'GET',
      {},
      ctx
    )
      .then((res) => res.data as File[])
      .then((files) => {
        return Object.values(files.map((file) => ({ ...file, selectable: !file.isDir && file.name !== 'metadata.json' })));
      });

    return res;

    // MOCK DATA
    // return Promise.resolve(searchMockData(data.path, RASTER_MOCK_DATA)).then((data) => {
    //   return data.map((file) => ({ ...file, selectable: !file.isDir && file.name !== 'metadata.json' }));
    // });
  }

  public async getDirectoryById(data: ExplorerGetById, ctx: IContext): Promise<File[]> {
    this.logger.info(`[StorageExplorerManagerRaster][getDirectoryById] fetching directory by id with data: ${JSON.stringify(data)}.`);

    const res = await requestExecutor(
      {
        url: `${this.service.url}/explorer/directorybyid?id=${data.id}`,
        exposureType: this.service.exposureType,
      },
      'GET',
      {},
      ctx
    )
      .then((res) => res.data as File[])
      .then((files) => {
        return Object.values(files);
      });

    return res;
  }

  public async getFile(data: ExplorerGetByPath, ctx: IContext): Promise<LayerRasterRecord> {
    this.logger.info(`[StorageExplorerManagerRaster][getFile] fetching file with data: ${JSON.stringify(data)}.`);

    // REAL LOGIC
    const res = await requestExecutor(
      {
        url: `${this.service.url}/explorer/file?path=${data.path}`,
        exposureType: this.service.exposureType,
      },
      'GET',
      {},
      ctx
    ).then((res) => res.data as LayerRasterRecord);

    return res;

    // MOCK DATA
    // return Promise.resolve(MOCK_FILE);
  }

  public async getStreamFile(data: ExplorerGetByPath, ctx: IContext): Promise<Stream> {
    this.logger.info(`[StorageExplorerManagerRaster][getStreamFile] fetching file from path: ${data.path}.`);

    const res = await requestExecutor(
      {
        url: `${this.service.url}/explorer/file?path=${data.path}`,
        exposureType: this.service.exposureType,
      },
      'GET',
      {
        responseType: 'stream',
      },
      ctx
    );

    return res.data as NodeJS.ReadableStream; // <-- this is a stream
  }

  /* FOR UPLOAD API */
  // For this to work, need to include the headers in the request.
  public async writeStreamFile(data: ExplorerGetByPath, file: Express.Multer.File, ctx: IContext): Promise<NodeJS.WritableStream> {
    this.logger.info(`[StorageExplorerManagerRaster][writeStreamFile] writing file in path: ${data.path}.`);

    const res = await requestExecutor(
      {
        url: `${this.service.url}/explorer/file?path=${data.path}`,
        exposureType: this.service.exposureType,
      },
      'POST',
      {
        responseType: 'stream',
        data: file,
      },
      ctx
    );

    return res.data as NodeJS.WritableStream; // <-- this is a stream
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  public async resolveMetadataAsModel({ metadata }: ExplorerResolveMetadataAsModel, ctx: IContext): Promise<LayerRasterRecord> {
    this.logger.info(`[StorageExplorerManagerRaster][resolveMetadataAsModel] resolve file metadata: ${JSON.stringify(metadata)}.`);

    const res = await Promise.resolve(JSON.parse(metadata) as LayerRasterRecord);

    return res;
  }

  public async getFileById(data: ExplorerGetById, ctx: IContext): Promise<LayerRasterRecord> {
    this.logger.info(`[StorageExplorerManagerRaster][getFileById] fetching file by id with data: ${JSON.stringify(data)}.`);

    const res = await requestExecutor(
      {
        url: `${this.service.url}/explorer/filebyid?id=${data.id}`,
        exposureType: this.service.exposureType,
      },
      'GET',
      {},
      ctx
    ).then((res) => res.data as LayerRasterRecord);

    return res;
  }

  public async getDecryptedId(data: ExplorerGetById, ctx: IContext): Promise<{ data: string }> {
    this.logger.info(`[StorageExplorerManagerRaster][getDecryptedId] decrypting id with data: ${JSON.stringify(data)}.`);

    const res = await requestExecutor(
      {
        url: `${this.service.url}/explorer/decryptid?id=${data.id}`,
        exposureType: this.service.exposureType,
      },
      'GET',
      {},
      ctx
    ).then((res) => res.data as { data: string });

    return res;
  }
}
