import { Field, ObjectType } from 'type-graphql';
import { footprintObject } from '../AUTOGENERATED/GraphQLClass';

@ObjectType()
export class SourceInfo {
  @Field((type) => String, { nullable: false })
  public srs: string; //crs: number

  @Field((type) => String, { nullable: false })
  public fileFormat: string;

  @Field((type) => Number, { nullable: false })
  public resolutionDegree: number; //pixelSize

  @Field((type) => footprintObject, { nullable: false })
  public extentPolygon: Record<string, unknown>; //extentPolygon
}
