import { Field, ObjectType } from 'type-graphql';
import { footprintObject } from '../AUTOGENERATED/GraphQLClass';

@ObjectType()
export class SourceValidation {
  @Field((type) => Boolean, { nullable: false })
  public isValid: boolean;

  @Field((type) => String, { nullable: true })
  public message?: string;

  @Field((type) => String, { nullable: true })
  public srs?: string; //crs: number

  @Field((type) => String, { nullable: true })
  public fileFormat?: string;

  @Field((type) => Number, { nullable: true })
  public resolutionDegree?: number; //pixelSize

  @Field((type) => footprintObject, { nullable: true })
  public extentPolygon?: Record<string, unknown>; //extentPolygon
}
